paths:
  uploads: /assets/images
  static: /

collections_config:
  pages:
    path: ''
    glob:
      - '**/*.html'
    name: Сторінки
    singular_name: Сторінка
    description: Усі сім сторінок сайту в одному розділі. Відкрийте сторінку та редагуйте текст безпосередньо на макеті.
    icon: wysiwyg
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
    _enabled_editors:
      - visual
